[package]
name = "vaccine-bin"
version = "0.1.0"
authors = ["Abhijat Malviya <malviya.abhijat@gmail.com>"]
edition = "2018"

[dependencies]
rest-client = { path = "../rest-client" }
schema-parser = { path = "../schema-parser" }
serde_json = "1.0.39"
clap = "2.33.0"
